"""
AI-Generated Text Detection Service
─────────────────────────────────────
Detects whether an interview answer was likely generated by an AI tool.
This is the LAST LINE OF DEFENSE — even if the proctor agent doesn't
detect the AI app, we can analyze the answer text itself.

Detection Methods:
  1. LINGUISTIC ANALYSIS — AI text has distinctive patterns
  2. TYPING BEHAVIOR ANALYSIS — Paste detection via timing
  3. CONSISTENCY SCORING — Compare answer style across turns
  4. VOCABULARY & STRUCTURE — AI uses specific patterns

This runs as part of the background evaluation pipeline.
"""

from __future__ import annotations

import logging
import math
import re
from collections import Counter
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class AIDetectionResult:
    """Result of AI-generated text analysis."""
    ai_probability: float          # 0.0 to 1.0 (0 = human, 1 = AI)
    confidence: str                # "low" | "medium" | "high"
    signals: list[dict]            # Individual detection signals
    verdict: str                   # "likely_human" | "uncertain" | "likely_ai"
    explanation: str               # Human-readable explanation
    penalty_multiplier: float      # 1.0 = no penalty, 0.5 = 50% score reduction


# ═══════════════════════════════════════════════════════════════════
#  SIGNAL DETECTORS
# ═══════════════════════════════════════════════════════════════════

def _detect_ai_patterns(text: str) -> list[dict]:
    """
    Detect linguistic patterns commonly found in AI-generated text.
    AI models have distinctive writing "fingerprints":
      - Overly structured with numbered lists
      - Hedging phrases ("It's important to note that...")
      - Perfect grammar with no conversational shortcuts
      - Specific transition phrases
      - Formulaic conclusions
    """
    signals = []
    lower = text.lower()
    words = text.split()
    word_count = len(words)

    if word_count < 20:
        return signals  # Too short to analyze

    # ── Signal 1: AI hedging phrases ──────────────────────────
    ai_hedging_phrases = [
        "it's important to note",
        "it's worth noting",
        "it is important to mention",
        "it is worth mentioning",
        "it's crucial to",
        "it's essential to",
        "in today's landscape",
        "in the modern landscape",
        "in a nutshell",
        "leveraging the power of",
        "harnessing the power",
        "at the end of the day",
        "in my experience as an ai",
        "as a language model",
        "i don't have personal experience",
        "let me break this down",
        "let me walk you through",
        "there are several key",
        "here's how i would approach",
        "great question",
        "that's a great question",
        "excellent question",
    ]
    hedge_count = sum(1 for phrase in ai_hedging_phrases if phrase in lower)
    if hedge_count >= 2:
        signals.append({
            "signal": "ai_hedging_phrases",
            "score": min(0.3, hedge_count * 0.1),
            "detail": f"Found {hedge_count} AI-typical hedging phrases",
        })

    # ── Signal 2: Over-structured with numbered lists ─────────
    numbered_items = len(re.findall(r'^\s*\d+[\.\)]\s', text, re.MULTILINE))
    bullet_items = len(re.findall(r'^\s*[-•*]\s', text, re.MULTILINE))
    list_items = numbered_items + bullet_items
    if list_items >= 4 and word_count < 300:
        signals.append({
            "signal": "over_structured_lists",
            "score": 0.2,
            "detail": f"Answer is overly structured ({list_items} list items in {word_count} words)",
        })

    # ── Signal 3: Unnaturally perfect grammar + no contractions ─
    contractions = [
        "i'm", "i've", "i'd", "i'll", "we're", "we've",
        "they're", "don't", "didn't", "doesn't", "won't",
        "can't", "couldn't", "wouldn't", "shouldn't",
        "it's", "that's", "there's", "here's", "what's",
    ]
    contraction_count = sum(1 for c in contractions if c in lower)

    # Check for formal alternatives
    formal_alternatives = [
        "i am", "i have", "i would", "i will", "we are",
        "they are", "do not", "did not", "does not",
        "will not", "cannot", "could not", "would not",
        "it is", "that is", "there is",
    ]
    formal_count = sum(1 for f in formal_alternatives if f in lower)

    if formal_count >= 4 and contraction_count == 0 and word_count > 80:
        signals.append({
            "signal": "no_contractions_formal_style",
            "score": 0.15,
            "detail": f"Unnaturally formal ({formal_count} formal phrases, 0 contractions)",
        })

    # ── Signal 4: AI transition phrases ───────────────────────
    ai_transitions = [
        "furthermore", "moreover", "additionally", "consequently",
        "in conclusion", "to summarize", "in summary",
        "first and foremost", "last but not least",
        "on the other hand", "having said that",
        "with that being said", "that being said",
        "from a high level", "at a high level",
        "to elaborate on that",
    ]
    transition_count = sum(1 for t in ai_transitions if t in lower)
    if transition_count >= 3:
        signals.append({
            "signal": "ai_transition_phrases",
            "score": 0.15,
            "detail": f"Found {transition_count} AI-style transition phrases",
        })

    # ── Signal 5: Suspiciously comprehensive coverage ─────────
    # AI tends to cover ALL possible points in a structured way
    section_headers = len(re.findall(
        r'(?:^|\n)\s*\*\*[^*]+\*\*\s*[:—-]', text
    ))
    if section_headers >= 3:
        signals.append({
            "signal": "structured_sections",
            "score": 0.2,
            "detail": f"Answer has {section_headers} structured sections (AI-typical formatting)",
        })

    # ── Signal 6: Vocabulary richness analysis ────────────────
    # AI text tends to have higher vocabulary diversity
    if word_count >= 50:
        unique_words = len(set(w.lower() for w in words))
        vocab_ratio = unique_words / word_count
        # Humans in interview settings typically: 0.45-0.65
        # AI-generated text typically: 0.65-0.85
        if vocab_ratio > 0.72:
            signals.append({
                "signal": "high_vocabulary_diversity",
                "score": 0.1,
                "detail": f"Vocabulary diversity {vocab_ratio:.2f} is unusually high for spoken answers",
            })

    # ── Signal 7: Sentence length uniformity ──────────────────
    # AI generates sentences of very uniform length
    # Humans vary a lot (short + long in same answer)
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if len(s.strip()) > 5]
    if len(sentences) >= 4:
        lengths = [len(s.split()) for s in sentences]
        avg_len = sum(lengths) / len(lengths)
        if avg_len > 0:
            variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)
            std_dev = math.sqrt(variance)
            cv = std_dev / avg_len  # coefficient of variation

            # Humans: CV > 0.5 (highly variable sentence lengths)
            # AI: CV < 0.3 (very uniform sentence lengths)
            if cv < 0.25 and len(sentences) >= 5:
                signals.append({
                    "signal": "uniform_sentence_length",
                    "score": 0.15,
                    "detail": f"Sentence lengths are suspiciously uniform (CV={cv:.2f})",
                })

    return signals


def _detect_paste_behavior(
    time_taken_seconds: int | None,
    word_count: int,
) -> list[dict]:
    """
    Detect if the answer was likely pasted rather than typed.
    Average typing speed: 40-60 WPM for thoughtful answers.
    If someone "types" 200 words in 30 seconds → paste detected.
    """
    signals = []

    if time_taken_seconds is None or time_taken_seconds <= 0 or word_count < 20:
        return signals

    # Calculate effective WPM
    minutes = time_taken_seconds / 60.0
    wpm = word_count / minutes if minutes > 0 else 0

    # Thresholds:
    # < 40 WPM: Normal thinking + typing
    # 40-80 WPM: Fast typist but possible
    # 80-150 WPM: Suspiciously fast (likely some paste)
    # > 150 WPM: Definitely pasted
    if wpm > 150:
        signals.append({
            "signal": "definite_paste_detected",
            "score": 0.4,
            "detail": f"Answer speed ({wpm:.0f} WPM) indicates text was pasted, not typed",
        })
    elif wpm > 100:
        signals.append({
            "signal": "probable_paste_detected",
            "score": 0.25,
            "detail": f"Answer speed ({wpm:.0f} WPM) is unusually fast for typed interview answers",
        })
    elif wpm > 80:
        signals.append({
            "signal": "fast_typing_detected",
            "score": 0.1,
            "detail": f"Answer speed ({wpm:.0f} WPM) is faster than typical interview responses",
        })

    return signals


def _detect_consistency_issues(
    current_answer: str,
    previous_answers: list[str] | None,
) -> list[dict]:
    """
    Check if answers are stylistically inconsistent.
    If a candidate suddenly switches from short casual answers to
    long formal answers → they may have started using AI mid-interview.
    """
    signals = []

    if not previous_answers or len(previous_answers) < 2:
        return signals

    current_word_count = len(current_answer.split())
    prev_word_counts = [len(a.split()) for a in previous_answers]
    avg_prev = sum(prev_word_counts) / len(prev_word_counts)

    # Sudden length increase
    if avg_prev > 0 and current_word_count > avg_prev * 3 and current_word_count > 100:
        signals.append({
            "signal": "sudden_length_increase",
            "score": 0.15,
            "detail": (
                f"Answer length ({current_word_count} words) suddenly jumped "
                f"from average ({avg_prev:.0f} words)"
            ),
        })

    # Formality shift
    def formality_score(text: str) -> float:
        lower = text.lower()
        contractions = sum(1 for c in ["i'm", "don't", "can't", "it's", "we're"] if c in lower)
        formals = sum(1 for f in ["furthermore", "additionally", "consequently", "therefore"] if f in lower)
        return formals - contractions

    prev_formality = [formality_score(a) for a in previous_answers]
    avg_formality = sum(prev_formality) / len(prev_formality)
    current_formality = formality_score(current_answer)

    if current_formality - avg_formality >= 3:
        signals.append({
            "signal": "formality_shift",
            "score": 0.15,
            "detail": "Writing style suddenly became much more formal than previous answers",
        })

    return signals


# ═══════════════════════════════════════════════════════════════════
#  MAIN ANALYSIS FUNCTION
# ═══════════════════════════════════════════════════════════════════

def analyze_answer_for_ai(
    answer: str,
    time_taken_seconds: int | None = None,
    previous_answers: list[str] | None = None,
) -> AIDetectionResult:
    """
    Comprehensive AI-generated text detection.

    Args:
        answer: The candidate's answer text
        time_taken_seconds: How long they took (for paste detection)
        previous_answers: Previous answers (for consistency checking)

    Returns:
        AIDetectionResult with probability, signals, and verdict.
    """
    all_signals: list[dict] = []

    # ── Layer 1: Linguistic pattern analysis ──────────────────
    all_signals.extend(_detect_ai_patterns(answer))

    # ── Layer 2: Paste / typing behavior ──────────────────────
    word_count = len(answer.split())
    all_signals.extend(_detect_paste_behavior(time_taken_seconds, word_count))

    # ── Layer 3: Consistency with previous answers ────────────
    all_signals.extend(_detect_consistency_issues(answer, previous_answers))

    # ── Calculate overall AI probability ──────────────────────
    total_score = sum(s["score"] for s in all_signals)
    ai_probability = min(1.0, total_score)  # Cap at 1.0

    # ── Determine confidence ──────────────────────────────────
    signal_count = len(all_signals)
    if signal_count >= 4 or any(s["score"] >= 0.3 for s in all_signals):
        confidence = "high"
    elif signal_count >= 2:
        confidence = "medium"
    else:
        confidence = "low"

    # ── Verdict ───────────────────────────────────────────────
    if ai_probability >= 0.60:
        verdict = "likely_ai"
        explanation = (
            f"High AI-generation probability ({ai_probability:.0%}). "
            f"Detected {signal_count} signals: "
            + "; ".join(s["detail"] for s in all_signals[:3])
        )
        penalty_multiplier = 0.5  # 50% score reduction
    elif ai_probability >= 0.35:
        verdict = "uncertain"
        explanation = (
            f"Moderate AI-generation signals ({ai_probability:.0%}). "
            f"Some patterns suggest possible AI assistance. "
            + "; ".join(s["detail"] for s in all_signals[:2])
        )
        penalty_multiplier = 0.8  # 20% score reduction
    else:
        verdict = "likely_human"
        explanation = f"No significant AI-generation signals detected ({ai_probability:.0%})."
        penalty_multiplier = 1.0  # No penalty

    return AIDetectionResult(
        ai_probability=round(ai_probability, 3),
        confidence=confidence,
        signals=all_signals,
        verdict=verdict,
        explanation=explanation,
        penalty_multiplier=penalty_multiplier,
    )
